import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import BrandMark from './components/BrandMark.jsx';
import './styles.css';
// Leave VITE_API_URL blank on Vercel so the browser calls the same site's /api route.
const API = import.meta.env.VITE_API_URL ?? '';
function App() {
 const [question,setQuestion]=useState('What is the evidence for urban trees reducing summer heat?'); const [result,setResult]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 async function research(e){e.preventDefault();setLoading(true);setError('');setResult(null);try{const r=await fetch(`${API}/api/research`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Research request failed.');setResult(d)}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <main><nav><a className="brand" href="#top"><BrandMark/><span>veritas</span><small>evidence studio</small></a><span className="status"><i/> Free-first sources</span></nav><section className="hero" id="top"><p className="eyebrow">RESEARCH WITH RECEIPTS</p><h1>Reach a clearer<br/><em>truth.</em></h1><p className="lede">Ask a question. Veritas gathers source-backed context, surfaces what it found, and creates a verification-ready record.</p><form onSubmit={research}><label htmlFor="question">Your research question</label><div className="ask"><input id="question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength="300" required/><button disabled={loading}>{loading?'Searching…':'Investigate →'}</button></div><p className="hint">Uses public Wikipedia and Crossref data in this MVP. Always open the sources and judge the evidence.</p></form></section>{error&&<p className="error" role="alert">{error}</p>}{result&&<section className="results"><div className="result-head"><div><p className="eyebrow">EVIDENCE BRIEF</p><h2>{result.question}</h2></div><span className="pill">{result.sources.length} sources</span></div><p className="summary">{result.summary}</p><div className="sources">{result.sources.map((s,i)=><article key={s.url}><span className="number">0{i+1}</span><div><p className="kind">{s.kind}</p><h3>{s.title}</h3><p>{s.excerpt}</p><a href={s.url} target="_blank" rel="noreferrer">Read source ↗</a></div></article>)}</div><aside><span>VERIFICATION RECORD</span><code>{result.verificationId}</code><p>{result.anchorStatus}</p></aside></section>}<footer><BrandMark/><span>Veritas MVP · evidence is a practice, not a verdict.</span></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
